### PR TITLE
merged

### PR DESCRIPTION
**Pull request by uloco**
I merged your fork into mine and fixed some installing issues under `/usr/share/icons`.
The name given in the file `cursor.theme` in the line with `Inherits` must be the same as the directory name installing. (It was `Custom-Cursors` but the folder is named `custom-cursors`)

### CODE REVIEW

**Comment by osendott** [comment]
thanks! is everything working good now in Ubuntu??

**Comment by uloco** [comment]
Nearly. I will need to add the `update-alternatives` part to the script, to make it a one click install. Perhaps we should  add an option, whether the user wants to install it in his home directory or globally. This would prevent cluttering the system if it is not needed on other distributions like Arch.

**Comment by uloco** [comment]
Could you implement this? The update-alternatives commands are the following:
After you copied the files to /usr/share/icons/custom-cursors, run
`sudo update-alternatives --install /usr/share/icons/default/index.theme x-cursor-theme /usr/share/icons/custom-cursors/cursor.theme 50`
`sudo update-alternatives --set x-cursor-theme /usr/share/icons/custom-cursors/cursor.theme`

**Comment by osendott** [comment]
sorry, yeah I'll take care of it ASAP. I've had A LOT of personal sh*t going on - things have been a mess. I'll try and get it if not tonight, in the morning. 

[edit]

i used the online-editor here @ github to add the code, but I can't test it.

**Pull request merged**
